### ISSUE TITLE
Support for Winamp

### ISSUE THREAD

**Issue by poetryofcode** [ungive/discord-music-presence#13]
### Describe the problem

Music Presence does not support Winamp as of yet.

It would be great to have support for Winamp, as I prefer it over foobar.

They still have a standalone desktop player for Windows, which should not be confused with their web-based platform. The download for it is a bit hidden in the website menu. I personally use it with the online features not installed and its just like it was back in the old days.

Winamp v5.9.2 Build 10042
Executable: winamp.exe

**Comment by jonasberge** [comment]
From a quick test Winamp doesn't appear to communicate what it is playing to the Windows media control interface. You can see for yourself by pressing your volume keys and seeing no information about the current song in the overlay in the top left of the screen. Is there a plugin you are using that gives that functionality? It's required for Music Presence to detect Winamp.

**Comment by poetryofcode** [comment]
> Is there a plugin you are using that gives that functionality? It's required for Music Presence to detect Winamp.

I dug around a bit and found an abandoned(?) plugin for that.

However, I found a community update project for Winamp called WACUP. It supports SMTC. 

However, it also appears to support Discord Rich Presence, so building a support for WACUP would henceforth look to be possible but at the current moment also a bit redundant.

Up to you really, if you want to use time to implement that. For me, I am happy with the solution I found built-in.

Sorry to take up your time on this, I had no idea of that project before. So at least something good came out of my inquiry. :P

**Comment by jonasberge** [comment]
It doesn't take much to add it, so I will add it anyway if everything works well!

**Comment by ungive** [comment]
Added WACUP and Winamp.

WACUP's winamp.exe and the official Winamp player have the same identifier on Windows (both report as `winamp.exe`). Because of this you will see WACUP's Winamp displayed as "Winamp" and not "WACUP":

wacup.exe
![image](https://github.com/user-attachments/assets/068df104-5d46-4f87-b802-c2c458d3472a)

wacup's winamp.exe
![image](https://github.com/user-attachments/assets/63658bae-4fe2-4e8c-8673-c40257a9b90c)

official winamp.exe
![image](https://github.com/user-attachments/assets/8d299c06-da07-4b81-be2d-587813f520de)

Thanks for reporting!
