### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JoeyNoProVN** [ungive/discord-music-presence#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The logo of the media player still shows even though I have disabled that.

### Reproduction Steps

Appearance > Show the logo of the media player > Uncheck this but the logo still shows

### Expected behavior

No media player logo near thumbnails

### Screenshots
<img width="983" alt="Ảnh chụp màn hình 2024-12-15 185749" src="https://github.com/user-attachments/assets/a9da0eec-5f78-48a4-8191-cde9726346d1" />

### Device Info

- Discord Music Presence version: 2.2.8
- Operating system: Windows 11 Pro, version 24H2, build 26100.2605
- The media I used: Spotify

**Comment by ungive** [comment]
This is intended, see the discussion in #46.

The setting is under the category "Settings for non-service media players", you can't disable the logo for streaming services, as some of them (TIDAL and Deezer, in the future likely Apple Music and Spotify too) make use of their respective APIs (e.g. the TIDAL API and Deezer API) and usage of those APIs requires branding and backlinks, which I want to adhere to.

If I add an option to hide the logo that *might* be ok now, but I have plans for Music Presence going forward (see the [roadmap](https://github.com/ungive/discord-music-presence/blob/master/documentation/roadmap.md)) and I don't want to regret it later. Removing the option to hide the logo again in a future version would most certainly upset users, so I'm enforcing it now to save myself any headaches later.

If Discord ever adds the option to put the logo elsewhere, so that it doesn't cover the album art, I'll be sure to incorporate that!
