### ISSUE TITLE
[Bug] TIDAL Presence shows wrong album.

### ISSUE THREAD

**Issue by MarvelousAdiris** [ungive/discord-music-presence#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes, Music Presence shows a different album from what I'm listening to.

### Reproduction Steps

1. Play a song on TIDAL
2. Click on Discord profile
3. See the error

### Expected behavior

Show the album I'm actually listening to.

### Screenshots

![imagen_2024-06-02_133042753](https://github.com/ungive/discord-music-presence/assets/171500907/799906a1-eabb-4474-88fd-b89c0aa1e576)
![imagen_2024-06-02_133202098](https://github.com/ungive/discord-music-presence/assets/171500907/93d76080-f12d-4e9b-aa63-6c3f8f1833a8)

![imagen_2024-06-02_134227843](https://github.com/ungive/discord-music-presence/assets/171500907/986090b5-31a5-4e59-a49f-22fe1d3d51d4)
![imagen_2024-06-02_134246898](https://github.com/ungive/discord-music-presence/assets/171500907/156d48b6-15f1-470b-9a52-c58efea749e5)

### Device Info

- Discord Music Presence version: 2.1.1
- Operating system: Windows 10
- The media player you used (if applicable): TIDAL

### Additional context

Happens extremely often with live albums. (shows the studio album the song came from instead.)

**Comment by ungive** [comment]
Thanks for the bug report. Unfortunately the TIDAL desktop app only reports the song title and artist, but not the album from which it is playing the song:

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/589a4803-c84a-4dfd-a607-22103223ed4e)

(nullopt meaning there is no data) 

The proper way to fix that is to contact TIDAL support and ask them kindly to report the album name as well, which is something others have done before with e.g. Spotify, see playerctl for instance: [letter-to-spotify-support.md](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md)

I could setup a generic message that is similar to the one I linked with the technical details that I, you and perhaps others could send to TIDAL support to raise awareness of the issue.

There is however a semi-solution, which involves getting the album image from the local media player (instead of the TIDAL API, which is how I do it at the moment), which would then show the correct album cover (but not the correct album name). That way the status would at least appear a bit more correct. This is something I will be working on soon.

**Comment by MarvelousAdiris** [comment]
Thank you for this response.

**Comment by ungive** [comment]
I have reported this issue with the following text. You may report it too my reusing the text (I have added a preamble explaining the source of the text):

- Report here: https://support.tidal.com/hc/en-us/requests/new
- Title: TIDAL is reporting incomplete media metadata to Windows
- Text:

> I am contacting you on behalf of an application/software developer which has experienced issue when interfacing with Apple Music for Windows through Windows system APIs. The following is his explanation of the issue. Here is also a link to a GitHub issue outlining the problem further: [github.com/ungive/discord-music-presence/issues/17](https://github.com/ungive/discord-music-presence/issues/17)
>
>TIDAL for Windows reports music metadata (title, artist, album, playback position, etc.) to the operating system, so that other applications can see what the TIDAL media player is currently playing. I am using a low-level C++ API, called WinRT, to access that information. When I attempt to read the album name it reports no information at all.
>
>The following low-level C++ functions (of the WinRT API) are used to retrieve this information:
Album: Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties.AlbumTitle()
Documentation: https://learn.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmediaproperties?view=winrt-22621
>
>The return value of AlbumTitle() is empty:
>
>Screenshot 1 (s1) contains the code that is used to retrieve the information.
>
>session is an instance of the C++ type “winrt::Windows::Media::Control::GlobalSystemMediaTransportControlsSession”.
>
>Screenshot 2 (s2) shows the contents of the variables of screenshot 1.
>
>As you can see the album title is empty. This information is useful and should be reported by TIDAL, so that it's possible to more distinctly distinguish which song exactly is playing (e.g. to retrieve the correct cover image or to know it's playing from the a single album or from a normal album or from a deluxe version of the album).
>
>It would be great if TIDAL could report more detailed information via system APIs in the future!
>
>Thank you.

Screenshots:

s1.png
![s1](https://github.com/ungive/discord-music-presence/assets/24623262/8053a78a-fee4-493f-b8ea-00098509d25f)

s2.png
![s2](https://github.com/ungive/discord-music-presence/assets/24623262/ac4f76a6-de49-446e-a569-e7ed4bc21798)

I'll close this issue, as this is not an issue with Music Presence anymore.

**Comment by MarvelousAdiris** [comment]
I think it's unnecessary for other users to send this letter yet, as TIDAL support should still read your request and email you back, but thank you anyway.

**Comment by ungive** [comment]
I reported the issue with the Chromium project: https://issues.chromium.org/issues/349310439
