### ISSUE TITLE
My media player is not detected although i playing music on window media player

### ISSUE THREAD

**Issue by finruhee** [ungive/discord-music-presence#33]
Players I am using, that aren't supported yet:
```
win_winrt: Chrome - Chrome (disabled)
signature: d0d54a67b34cda0d
```

---

**Comment by ungive** [comment]
Hey, thanks for reporting! Three things:
- The attached information suggests that you never played media with the Windows Media Player. Music Presence detects any application that shares media and logs the application name and executable name, to help with solving this issue.
- My suspicion is that you used the old Windows Media Player ([Wikipedia](https://de.wikipedia.org/wiki/Windows_Media_Player))? That application does not report any playback information to Windows, that you can then control via the media control center, like other media players do. It's simply not maintained anymore by Microsoft. Music Presence only works with the new Windows Media Player ([Wikipedia](https://en.wikipedia.org/wiki/Windows_Media_Player_(2022))). Confusingly it has the same name.
- The newer version of the Windows Media Player is disabled by default in the Music Presence menu, so you will have to enable it manually. This is because of the reasons listed [here](https://github.com/ungive/discord-music-presence/issues/4), mainly

> The media player must be a player specifically for music and not a multimedia player, like a browser or VLC media player. In any other case, multimedia players won't get support and will never be enabled by default because media like videos are not intended to be shown in the Discord status by Music Presence. Picture this: You have Music Presence running in the background and you watch your favourite YouTube video and you forget that it's shown in your Discord status, even though you might not want that.

If you are using the newer version of the Windows Media Player, let me know. Could you attach some screenshots of you playing media and the song info that is visible in the media control center/media control overlay?

**Comment by finruhee** [comment]
this is my window media player on microsoft window 11 version 23h2 (os build 22631.4037)
![image](https://github.com/user-attachments/assets/2b035ee6-18ba-4a8a-82d1-59ade34a2cd7)

**Comment by finruhee** [comment]
here is music presence log
[presence.log](https://github.com/user-attachments/files/16726380/presence.log)

**Comment by ungive** [comment]
I experience this issue as well, on both Windows 10 and 11, Windows Media Player sometimes works and then all of a sudden doesn't anymore. It's not caused by Music Presence though, the data that the Windows Media Player reports is simply empty:

![grafik](https://github.com/user-attachments/assets/189fa0a7-f29b-43d6-be48-7b11666b7c87)

As you can see there is exactly one media session, "ZuneMusic" is the Windows Media Player and the song title is empty (NULL).

I recommend using a different media player, like MusicBee or foobar2000. Let's hope Microsoft gets wind of it and fixes it.
