### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by naturbrilian** [ungive/discord-music-presence#78]
Players I am using, that aren't supported yet:
```
version: 2.2.4
win_winrt: JellyfinMediaPlayer.exe - JellyfinMediaPlayer.exe (disabled)
signature: b7af8fc8813ff341
```

---

**Comment by ungive** [comment]
Added! Should be detected after restarting Music Presence.

At the moment it will have this slightly shifted down icon because I messed up creating it.
This is because Discord caches the image for a year and I can't work around that without a Music Presence update.

![image](https://github.com/user-attachments/assets/556bc9ec-964b-4b88-af24-42cd848459af)

Just a side note.
